---
- name: Add telegraf repository
  yum_repository:
    name: influxdb
    description: InfluxDB Repository - RHEL
    baseurl: https://repos.influxdata.com/rhel/$releasever/$basearch/stable
    gpgcheck: no
    enabled: yes
  tags:
     - centos

- name: Install telegraf
  yum:
    name: telegraf
    state: present

- name: Backup telegraf default config
  command: mv /etc/telegraf/telegraf.conf /etc/telegraf/telegraf.conf-default

- name: Copy telegraf config file
  template:
    src: "telegraf.conf.j2"
    dest: "/etc/telegraf/telegraf.conf"

- name: Restart service telegraf
  service:
    name: telegraf
    state: restarted

- name: Enable service telegraf
  service:
    name: telegraf
    enabled: yes
