---
- name: Add telegraf repository
  yum_repository:
    name: influxdb
    description: InfluxDB Repository - RHEL
    baseurl: https://repos.influxdata.com/rhel/$releasever/$basearch/stable
    gpgcheck: no
    enabled: yes
  tags:
     - centos

- name: Install telegraf
  yum:
    name: telegraf
    state: present
  tags:
     - centos

- name: Set hostname
  shell: hostname
  register: telegraf_hostname
  run_once: true
  tags:
     - centos

- set_fact:
    telegraf_hostname: "{{ telegraf_hostname.stdout }}"
  tags:
     - centos

- debug: var=telegraf_hostname
  run_once: true
  tags:
     - centos

- name: Backup telegraf default config
  command: mv /etc/telegraf/telegraf.conf /etc/telegraf/telegraf.conf-default
  tags:
     - centos

- name: Copy telegraf config file
  template:
    src: "telegraf.conf.j2"
    dest: "/etc/telegraf/telegraf.conf"
  tags:
     - centos

- name: Restart service telegraf
  service:
    name: telegraf
    state: restarted
  tags:
     - centos

- name: Enable service telegraf
  service:
    name: telegraf
    enabled: yes
  tags:
     - centos
